# Generated by Django 2.1.5 on 2020-01-29 06:04

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('about', models.TextField(default='暂无介绍', null=True, verbose_name='关于')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='简述')),
                ('pub_date', models.DateTimeField(verbose_name='发布日期')),
                ('up_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日期')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('tag', models.CharField(choices=[('ME', '杂记'), ('TE', '杂技')], max_length=10, verbose_name='标签')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='访问量')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Auth')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
